name: ServiceNow Pull Request Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sn_instances/nowlearning-nlinst04150617-1vgvc-0001

jobs:
  build:
    name: Run ATF on dev instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowSourceInstance: ${{ secrets.NOW_DEV_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: Run ATF Test Suite
        id: atf_test_dev
        uses: ServiceNow/sncicd-tests-run@2.0.0
        with:
          testSuiteSysId: ${{ secrets.TEST_SUITE_ID}}
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.NOW_DEV_INSTANCE }}
